---
title: "Example Report"
author: "Henry Hansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load in guage station data
```{r}
stn274 <- Riverwave::smhi_csv(274)
head(stn274)
```

## Generate flood frequency data from stn274
```{r}
ggdt <- floo(stn274)
head(ggdt)
```

## Calculate exceedence probabilities and plot return period
```{r}
out <- excd(ggdt, "Vattenföring", 0.44)
# See exceedence plot
plot(out$TpEst,out$Vattenföring,
     xlab = "Return Period (years)",
     ylab = expression(paste("Discharge m"^"3"/"s")),
     cex.lab=1.2,
     mgp=c(2,1,0))
```

## Fit lognormal distribution using bayesian fitting procedure
```{r}
# # load brms for bayesian fit
library(brms)

# fit lognormal distribution using a bayesian approach
fit <- brm(Vattenföring ~ 1, data = out, family = lognormal())

# see summary of model results
summary(fit)

# see plot of model results
plot(fit)

# plot posterior predictive checks
pp_check(fit, ndraws = 50)

# declare posterior values
post <- posterior_summary(fit)

# plot resulting distribution and fitted distribution
hist(out$Vattenföring, freq = F, breaks = 10)
curve(dlnorm(x, meanlog=post[1,1], sdlog=post[2,1]), from = 0, to = max(out$Vattenföring), add = T)

```

## Calculate frequency factors

```{r}
# # test function
m <- post[1,1] #grab mean from posterior
s <- post[2,1] #grad sd from posterior

q100 <- FF_LogNormal(m, s , 0.01) #calculate q100

# Standard Return Intervals
ReturnInterval <- c(1.0101,2,5,10,15,25,30,35,40,45,50,60,70,80,90,100,150,200)

# Show p values for frequency factor calculations
(1/ReturnInterval)

# show expected discharge for 1 in 100 year flood
exp(q100)

#calculate flow at which a 2 year flood would happen
q2 <- FF_LogNormal(m, s , 0.5) 
exp(q2)
```

## Plot riverwave using q2
```{r}
riverwave_plot(stn274,q2)
```

